 # Problem Set 2

 # Question 1
Consider the following Python module:

a = 0

def b():
 
 global a

a = c(a)

def c(a):
 
 return a + 2

After importing the module into the interpreter, you execute:
>>> b()
>>> b()
>>> b()
>>> a
?
What value is displayed when the last expression (a) is evaluated? Explain your
answer by indicating what happens in every executed statement.

# Answer Question 1:

a is a global variable, therefore a is out of the affect of the funtions created. So a=0

 # Question 2
 Modify function fileLength() so that a
friendly message is printed instead:
>>> fileLength('midterm.py')
358
>>> fileLength('idterm.py')
File idterm.py not found.

In [161]:
# Answer Question 2:

def filelength(filename):
    try:
    
        file = open(filename)
        contents = file.read()
        file.close()
        print(len(contents))
    
    except FileNotFoundError:
        print('File idterm.py not found')
        
    
filelength('midterm.py')

File idterm.py not found

In [242]:
 # Question 3:
Write a class named Marsupial that can be used as shown below:
>>> m = Marsupial()
>>> m.put_in_pouch('doll')
>>> m.put_in_pouch('firetruck')
>>> m.put_in_pouch('kitten')
>>> m.pouch_contents()
['doll', 'firetruck', 'kitten']
Now write a class named Kangaroo as a subclass of Marsupial that inherits all the
attributes of Marsupial and also:
a. extends the Marsupial __init__ constructor to take, as input, the
coordinates x and y of the Kangaroo object,
b. supports method jump that takes number values dx and dy as input and
moves the kangaroo by dx units along the x-axis and by dy units along the yaxis, and
c. overloads the __str__ operator so it behaves as shown below.
>>> k = Kangaroo(0,0)
>>> print(k)
I am a Kangaroo located at coordinates (0,0)
>>> k.put_in_pouch('doll')
>>> k.put_in_pouch('firetruck')
>>> k.put_in_pouch('kitten')
>>> k.pouch_contents()
['doll', 'firetruck', 'kitten']
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> k.jump(1,0)
>>> print(k)
I am a Kangaroo located at coordinates (3,0)

SyntaxError: invalid syntax (<ipython-input-242-730ef084434b>, line 2)

# Answer question 3:



class Marsupial:
    

    def __class__(self, xput_in_pouch=0, yput_in_pouch=0, zput_in_pouch=0):
        
        self.x = xput_in_pouch
        self.y = yput_in_pouch
        self.z = zput_in_pouch

    def setx(self, xput_in_pouch):
        self.x = xput_in_pouch

    def sety(self, yput_in_pouch):
        self.y = yput_in_pouch
    
    def setz(self, zput_in_pouch):
        self.z = zput_in_pouch

    def get(self):
        pouch_contents = string (self.x, self.y, self.z)
        return (pouch_contents)
    
m = Marsupial ['doll', 'firetruck', 'kitten']
m.get()

Class Kangaroo:
    
    def __init_subclass__(self, dx = 0, dy = 0)
        
        self.x += dx
        self.y += dy
        
    
    def jump(self, dx, dy):
        
        self.x += dx
        self.y += dy
                
        return ('I am a Kangaroo located at coordinates ({},{})'. format (self.x, self.y))
        
k=Kangaroo()
print(k)

In [ ]:
 # Question 4:
    
Write function collatz() that takes a positive integer x as input and prints the
Collatz sequence starting at x. A Collatz sequence is obtained by repeatedly applying
this rule to the previous number x in the sequence:
x = {
𝑥/2 𝑖𝑓 𝑥 𝑖𝑠 𝑒𝑣𝑒𝑛
3𝑥 + 1 𝑖𝑓 𝑥 𝑖𝑠 𝑜𝑑𝑑
Your function should stop when the sequence gets to number 1. Your
implementation must be recursive, without any loops.
    >>> collatz(1)
1
>>> collatz(10)
10
5
16
8
4
2
1
+.

In [239]:
 # Answer Question 4:

def Collatz(x):
    if x>1:
        if x%2 == 0:
            print(int(x))
            Collatz(x/2)
        else:
            print(int(x))
            Collatz((3*x)+1)
    else:
        print("+.")
        
        
Collatz(10)

10
5
16
8
4
2
+.

In [184]:
 # Question 5
Write a recursive method binary() that takes a non-negative
integer n and prints the binary representation of integer n.
>>> binary(0)
0
>>> binary(1)
1
>>> binary(3)
11
>>> binary(9)
1001

1

# Answer question 5:

def binary(n):
    if n<0:
        print('Enter a non-negative integer')
    if n>=1:
        binary(n//2)
        print(n%2,end=' ')
    else:
        print('0')
    
binary(3)

In [ ]:
 # Question 6
Implement a class named HeadingParser that can be used to parse an HTML
document, and retrieve and print all the headings in the document. You should
implement your class as a subclass of HTMLParser, defined in Standard Library
module html.parser. When fed a string containing HTML code, your class should
print the headings, one per line and in the order in which they appear in the
document. Each heading should be indented as follows: an h1 heading should have indentation 0, and h2 heading should have indentation 1, etc. Test your
implementation using w3c.html.
>>> infile = open('w3c.html')
>>> content = infile.read()
>>> infile.close()
>>> hp = HeadingParser()
>>> hp.feed(content)
W3C Mission
Principles

 # Answer question 6:
 
from urllib.request import urlopen

def getSource(url): #search for the webpages
    response = urlopen(url)
    html = response.read()
    return html.decode()

def feedParser (self): # read the page
    infile = open('w3c.html')
    content = infile.read()
    infile.close()
        
from html.parser import HTMLParser
parser = HTMLParser()
parser.feed(content)   #feed the strings of the page into parser

class HeadingParser(HTMLParser):
    
    def__init__(self):
        
        HTMLParser.__init__(self)
        self.indent=0
    
    def handler_starttag(self,tag,attrs):
        
        for tag not in {'br','p'}: # p is the paraghraph element, br is the line break element. IF a tag is not a paraghraph element, tag is a header
            
            print('/n{}{}start'.format(self.indetn*' ',tag))
            self.indent+=4

In [ ]:
 # Question 7
    
Implement recursive function webdir() that takes as input: a URL (as a string) and
non-negative integers depth and indent. Your function should visit every web
page reachable from the starting URL web page in depth clicks or less, and print
each web page's URL. As shown below, indentation, specified by indent, should
be used to indicate the depth of a URL.
>>>
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html'
, 2, 0)
http://reed.cs.depaul.edu/lperkovic/csc242/test1.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test2.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test3.html
 http://reed.cs.depaul.edu/lperkovic/csc242/test4.html

 # Answer question 7:
 
class Crawler:
    def __init__(self):
        self.visited = set()
        
    def webdir(self, url, depth, indent):
        links = analyze(url)
        sekf.visited.add(url)
        
        for link in links:
            if link not in self.visited:
                try:
                    if depth >= 0:
                        
                        indent = 0
                        
                        for click in depth: 
                        
                            self.webdir(link, depth, indent)
                            print(url)
                            self.indent =+1
                            
                    else:
                        pass
                except:
                    pass
                
webdir('http://reed.cs.depaul.edu/lperkovic/csc242/test1.html', 2, 0)

In [ ]:
 # Question 8
    
Write SQL queries on the below database table that return:
a) All the temperature data.
b) All the cities, but without repetition.
c) All the records for India.
d) All the Fall records.
e) The city, country, and season for which the average rainfall is between 200
and 400 millimeters.
f) The city and country for which the average Fall temperature is above 20
degrees, in increasing temperature order.
g) The total annual rainfall for Cairo.
h) The total rainfall for each season.

In [ ]:
 # ref for question 8:
City Country Season Temperature
(C)
Rainfall
(mm)
Mumbai India Winter 24.8 5.9
Mumbai India Spring 28.4 16.2
Mumbai India Summer 27.9 1549.4
Mumbai India Fall 27.6 346.0
London United Kingdom Winter 4.2 207.7
London United Kingdom Spring 8.3 169.6
London United Kingdom Summer 15.7 157.0
London United Kingdom Fall 10.4 218.5
Cairo Egypt Winter 13.6 16.5
Cairo Egypt Spring 20.7 6.5
Cairo Egypt Summer 27.7 0.1
Cairo Egypt Fall 22.2 4.5

 # Answer Question 8: Write SQL queries:

    
import sqlite3

con = sqlite3.connect('web.db')

cur = con.cursor()

cur.execute("CREATE TABLE Weather (City text, Country text, Season text, Temperature(C) real,Rainfall(mm) real)")

cur.execute("INSERT INTO Weather VALUES ('Mumbai', 'India', 'Winter', 24.8, 5.9)")

cur.execute("INSERT INTO Weather VALUES ('Mumbai', 'India', 'Spring', 28.4, 16.2)")

cur.execute("INSERT INTO Weather VALUES ('Mumbai', 'India', 'Summer', 27.9 1549.4)")

cur.execute("INSERT INTO Weather VALUES ('Mumbai', 'India', 'Fall', 27.6, 346.0)")

cur.execute("INSERT INTO Weather VALUES ('London', 'United Kingdom', 'Winter', 4.2, 207.7)")

cur.execute("INSERT INTO Weather VALUES ('London', 'United Kingdom', 'Spring',8.3 , 169.6)")

cur.execute("INSERT INTO Weather VALUES ('London', 'United Kingdom', 'Summer', 15.7 , 157.0)")

cur.execute("INSERT INTO Weather VALUES ('London', 'United', 'Kingdom', 'Fall', 10.4 , 218.5)")

cur.execute("INSERT INTO Weather VALUES ('Cairo', 'Egypt', 'Winter', 13.6, 16.5)")

cur.execute("INSERT INTO Weather VALUES ('Cairo', 'Egypt', 'Spring', 20.7, 6.5)")

cur.execute("INSERT INTO Weather VALUES ('Cairo', 'Egypt', 'Summer', 27.7, 0.1)")

cur.execute("INSERT INTO Weather VALUES ('Cairo', 'Egypt', 'Fall', 22.2, 4.5)")


   
    # Question a: All the temperature data.
        
    SELECT Temperature FROM Weather
    
    # Question b: All the cities, but without repetition.
     
    SELECT DISTINCT City FROM Weather 
    
    # question c: All the records for India.
    
    SELECT * FROM Weather 
    WHERE Country = 'India'
    
    # question d: All the Fall records.
    
    SELECT * FROM Weather 
    WHERE Season = 'Fall'
    
    # question e: The city, country, and season for which the average rainfall is between 200
and 400 millimeters.
    
    SELECT City, Country, Season 
    FROM Weather 
    WHERE Rainfall BETWEEN 200 and 400
    
    # question f: The city and country for which the average Fall temperature is above 20
degrees, in increasing temperature order.

    SELECT City, Country FROM Weather 
    WHERE Season = 'Fall' and Temperature > 20 
    ORDER BY Temperature ASC

    # question g: The total annual rainfall for Cairo.
    
    SELECT SUM(Rainfall) FROM Weather 
    Where Country = 'Cairo'
    
    # question h: The total rainfall for each season.
    
    SELECT SUM(Rainfall) FROM Weather 
    GROUP BY Season

In [ ]:
 # Question 9
. Suppose list words is defined as follows:
>>> words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over',
'the', 'lazy', 'dog']
Write list comprehension expressions that use list words and generate the following
lists:
a) ['THE', 'QUICK', 'BROWN', 'FOX', 'JUMPS', 'OVER', 'THE',
'LAZY', 'DOG']
b) ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog']
c) [3, 5, 5, 3, 5, 4, 3, 4, 3] (the list of lengths of words in list
words).
d) [['THE', 'the', 3], ['QUICK', 'quick', 5], ['BROWN',
'brown', 5], ['FOX', 'fox', 3], ['JUMPS', 'jumps', 5],
['OVER', 'over', 4], ['THE', 'the', 3], ['LAZY', 'lazy',
4], ['DOG', 'dog', 3]] (the list containing a list for every word of list
words, where each list contains the word in uppercase and lowercase and the
length of the word.)
e) ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the',
'lazy', 'dog'] (the list of words in list words containing 4 or more
characters.)

In [ ]:
 # Answer Question 9:
    # a: [word.capitalize() for word in words]
    # b: [word.lowercase() for word in words]
    # c: [(word,len(word)) for word in words]
    # d: [[word.uppercase(), word.lowercase(),(word,len(word))] for word in words]
    # e: [[(c,word) for c in word if c >= 4] for word in words]